# Generated by Django 4.0.2 on 2022-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='CodedName',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='Definition',
            field=models.TextField(default='---empty---'),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='Level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='MKBSA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='MKKeyword',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='MKSubclass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='Note',
            field=models.TextField(default='---empty---'),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='PreferredName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='Remark',
            field=models.TextField(default='---empty---'),
        ),
        migrations.AddField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='VersionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='RevisionNumber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eclass7_1_cc_en_01_190102xx',
            name='VersionNumber',
            field=models.FloatField(default=0),
        ),
    ]
